default:
  root_dir: "/Users/Olsonac-admin/Documents/current/PKU/PKU_child_adult_meta_analysis"
  
speed_accuracy_function_summary:
  root_dir: "/Users/Olsonac-admin/Documents/current/PKU/PKU_child_adult_meta_analysis"
  results_dir: "results/speed_accuracy_analysis_results_tables"
  file_control_file: "src_table_extract/sa_file_control_file.csv"
  line_control_file: "src_table_extract/sa_line_control_file.csv"
  column_control_file: "src_table_extract/sa_column_control_file.csv"
  output_file: "results/speed_accuracy_analysis_results_tables/sa_summary_table.csv"
  file_list_output_file: "results/speed_accuracy_analysis_results_tables/sa_file_list.csv"
  
adults_function_summary:
  root_dir: "/Users/Olsonac-admin/Documents/current/PKU/PKU_child_adult_meta_analysis"
  results_dir: "results/function_results_tables"
  file_control_file: "src_table_extract/adult_functions_file_control_file.csv"
  line_control_file: "src_table_extract/adult_functions_line_control_file.csv"
  column_control_file: "src_table_extract/adult_functions_column_control_file.csv"
  output_file: "results/function_results_tables/adult_functions_summary_table.csv"
  file_list_output_file: "results/function_results_tables/adult_functions_file_list.csv"
  
children_function_summary:
  root_dir: "/Users/Olsonac-admin/Documents/current/PKU/PKU_child_adult_meta_analysis"
  results_dir: "results/function_results_tables"
  file_control_file: "src_table_extract/children_functions_file_control_file.csv"
  line_control_file: "src_table_extract/children_functions_line_control_file.csv"
  column_control_file: "src_table_extract/children_functions_column_control_file.csv"
  output_file: "results/function_results_tables/children_functions_summary_table.csv"  
  file_list_output_file: "results/function_results_tables/children_functions_file_list.csv"
  
overall_function_summary: 
  root_dir: "/Users/Olsonac-admin/Documents/current/PKU/PKU_child_adult_meta_analysis"
  results_dir: "results/function_results_tables"
  file_control_file: "src_table_extract/overall_functions_file_control_file.csv"
  line_control_file: "src_table_extract/overall_functions_line_control_file.csv"
  column_control_file: "src_table_extract/overall_functions_column_control_file.csv"
  output_file: "results/function_results_tables/overall_functions_summary_table.csv"
  file_list_output_file: "results/function_results_tables/overall_functions_file_list.csv"
  
adult_effect_size_function_summary: 
  root_dir: "/Users/Olsonac-admin/Documents/current/PKU/PKU_child_adult_meta_analysis"
  results_dir: "results/function_results_tables"
  file_control_file: "src_table_extract/es_adult_file_control_file.csv"
  line_control_file: "src_table_extract/es_adult_line_control_file.csv"
  column_control_file: "src_table_extract/es_adult_column_control_file.csv"
  output_file: "results/ES_analysis_results_tables/adult_es_functions_summary_table.csv"
  file_list_output_file: "results/ES_analysis_results_tables/adult_es_functions_file_list.csv"
  
within_age_effect_size_summary: 
  root_dir: "/Users/Olsonac-admin/Documents/current/PKU/PKU_child_adult_meta_analysis"
  results_dir: "results/ES_analysis_results_tables"
  file_control_file: "src_table_extract/es_sum_file_control_file.csv"
  line_control_file: "src_table_extract/es_sum_line_control_file.csv"
  column_control_file: "src_table_extract/es_sum_column_control_file.csv"
  output_file: "results/ES_analysis_results_tables/within_age_es_summary_table.csv"
  file_list_output_file: "results/ES_analysis_results_tables/within_age_es_file_list.csv"
  
adult_effect_size_summary: 
  root_dir: "/Users/Olsonac-admin/Documents/current/PKU/PKU_child_adult_meta_analysis"
  results_dir: "results/ES_analysis_results_tables"
  file_control_file: "src_table_extract/es_adult_sum_file_control_file.csv"
  line_control_file: "src_table_extract/es_adult_sum_line_control_file.csv"
  column_control_file: "src_table_extract/es_adult_sum_column_control_file.csv"
  output_file: "results/ES_analysis_results_tables/adult_es_summary_table.csv"
  file_list_output_file: "results/ES_analysis_results_tables/adult_es_file_list.csv"
  
children_effect_size_summary: 
  root_dir: "/Users/Olsonac-admin/Documents/current/PKU/PKU_child_adult_meta_analysis"
  results_dir: "results/ES_analysis_results_tables"
  file_control_file: "src_table_extract/es_children_sum_file_control_file.csv"
  line_control_file: "src_table_extract/es_children_sum_line_control_file.csv"
  column_control_file: "src_table_extract/es_children_sum_column_control_file.csv"
  output_file: "results/ES_analysis_results_tables/children_es_summary_table.csv"
  file_list_output_file: "results/ES_analysis_results_tables/children_es_file_list.csv"
  
children_effect_size_function_summary: 
  root_dir: "/Users/Olsonac-admin/Documents/current/PKU/PKU_child_adult_meta_analysis"
  results_dir: "results/function_results_tables"
  file_control_file: "src_table_extract/es_children_file_control_file.csv"
  line_control_file: "src_table_extract/es_children_line_control_file.csv"
  column_control_file: "src_table_extract/es_children_column_control_file.csv"
  output_file: "results/ES_analysis_results_tables/children_es_functions_summary_table.csv"
  file_list_output_file: "results/ES_analysis_results_tables/children_es_functions_file_list.csv"
